### ISSUE TITLE
[↷] Feature request: OpenTrack support

### ISSUE THREAD

**Issue by r57zone** [infinitellamas/Arduino-Tracker-Plugin#1]
Support [OpenTrack](https://github.com/opentrack/opentrack) for [Arduino tracker with GY-85](https://github.com/Razor-AHRS/razor-9dof-ahrs), MPU6050 or etc. OpenTrack has different filters, and can also adjust the sensitivity and so on. OpenTrack will give stability to Arduino head tracking rotation. 

To support OpenTrack need change output to "UDP over network", open udp server 4242 port and read data from this. For example [implementation on Delphi](https://github.com/r57zone/Steering-wheel-for-PC-with-OpenTrack-and-Android/blob/master/Project1.dpr#L315-L342).
Package type (all values float):
x y z yaw pitch roll
(x y z - do not need to use)
[Convert to quaternion](https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles) from the yaw pitch roll.

```
static Quaterniond toQuaternion(double pitch, double roll, double yaw)
{
	Quaterniond q;
	double t0 = std::cos(yaw * 0.5);
	double t1 = std::sin(yaw * 0.5);
	double t2 = std::cos(roll * 0.5);
	double t3 = std::sin(roll * 0.5);
	double t4 = std::cos(pitch * 0.5);
	double t5 = std::sin(pitch * 0.5);

	q.w() = t0 * t2 * t4 + t1 * t3 * t5;
	q.x() = t0 * t3 * t4 - t1 * t2 * t5;
	q.y() = t0 * t2 * t5 + t1 * t3 * t4;
	q.z() = t1 * t2 * t4 - t0 * t3 * t5;
	return q;
}
```

Thanks.

**Comment by terminal29** [comment]
Opentrack support, while it is a good idea, would be suited to it's own ovsvr plugin.

**Comment by r57zone** [comment]
If you are interested in making a plugin with OpenTrack support, then can do it right away for the Steam driver, here is the [ready driver](https://github.com/r57zone/OpenVR-head-tracking-with-buttons), with the rotation of the head, using the buttons.

OpenTrack already has everything need, for example, can make a reset button and so on.

**Comment by terminal29** [comment]
I think i would prefer to make an opentrack plugin for osvr because I know how osvr works and it is much easier to configure what goes where, but your steamvr driver looks very nice and I really want to have osvr defined controllers working in steamvr so I'll probably end up using your project as a base if that is ok.

**Comment by r57zone** [comment]
[Implementation](https://github.com/r57zone/OpenTrack-UDP-receive) for read output interface of OpenTrack on WinSock and C.

**Comment by terminal29** [comment]
https://github.com/infinitellamas/OSVR-Opentrack
@r57zone Thanks for the base code, I've packaged it into an osvr plugin, please tell me if it works or not. I've tested it with the opentrack sine wave example and that part works but I don't know if i have the correct ordering with the rotation angles.

**Comment by r57zone** [comment]
Thanks, in the near future I will test and write.

UPD: Works, thank you.
