### ISSUE TITLE
Feature Request: Drift compensation

### ISSUE THREAD

**Issue by L3nyxx** [infinitellamas/Arduino-Tracker-Plugin#2]
Hi @infinitellamas. I was wondering if it would be feasible to implement some sort of yaw-drift compensation as I noticed that it gets progressively worse the longer I use it? I know that the mpu-6050 lacks a magnetometer so perhaps we could add one to it or use another cheap mpu like the 9250.

**Comment by terminal29** [comment]
I'll take a look at implementing this in the rewrite. 
I'll also try and add a keyboard button/controller button that you can press to reset yaw in case the compensation doesn't work properly.

**Comment by r57zone** [comment]
The [firmware for the GY 85 / MPU 9250](https://github.com/Razor-AHRS/razor-9dof-ahrs/tree/master/Arduino/Razor_AHRS) write to serial:
> #YPR=-142.28,-5.38,33.52
It would be nice to add support.

**Comment by L3nyxx** [comment]
Hi @infinitellamas. I tried out the latest build and overall it seems to work well. I like the calibration feature since I no longer have to flash the calibration sketch or enter the com number into console. I did however run into a problem while playing Doom 3 BFG VR. The tracking would start spinning uncontrollably and would only stop when I re-calibrated it. I'm not sure what caused this but it has happened a few times only with Doom. I don't seem to have this problem with other games.

**Comment by terminal29** [comment]
Hmm. Yeah I had that tracking problem too but I assumed that it must just be my chip because it was so random. I think i know what it might be

**Comment by terminal29** [comment]
[inf_osvr_arduino.zip](https://github.com/infinitellamas/Arduino-Tracker-Plugin/files/1100918/inf_osvr_arduino.zip)

This should fix it, I've had it run for about 20 mins and it doesn't seems to spaz out anymore

**Comment by L3nyxx** [comment]
I was able to reproduce the problem running Doom 3 BFG VR. It even lost tracking at one point and was able to reconnect by resetting the nano (thanks for that feature btw). It did seem to run stable after a while though. Seems that the spazzing out happens like a minute after the game is loaded.

**Comment by terminal29** [comment]
I'll take a look tomorrow but I'm fairly certain that it's something I've missed in rewriting the arduino code.

**Comment by terminal29** [comment]
[inf_osvr_arduino.zip](https://github.com/infinitellamas/Arduino-Tracker-Plugin/files/1103918/inf_osvr_arduino.zip)
@L3nyxx Could you try this one. I only changed the arduino code so you shouldnt need to update the osvr plugin.

**Comment by L3nyxx** [comment]
Hi @infinitellamas. I played Doom for a couple of minutes and restarted it a few times to test it and the problem seems to be fixed. It no longer spins out. Thanks.

**Comment by terminal29** [comment]
Sweet! I still have no clue what it was but I'm glad it's fixed. I'm trying to add a reset-yaw button combo and when that's done ill add a new release

**Comment by terminal29** [comment]
Ok I have uploaded a new release, with a key combo to reset the current rotation to identity. Please tell me if this is a) working properly, and b) a fix for this issue. cheers

**Comment by L3nyxx** [comment]
The new release is great! There is very little drift and the new yaw reset feature is instantaneous. I was using a batch file to launch osvr_reset_yaw.exe before which takes a few seconds to complete. Your implementation is much better. I redid the room setup and found that I needed to face the back wall to align it correctly. Is there anyway to change it so that it centers with the front facing arrow on the steamvr floor? Apart from that everything works well.

**Comment by terminal29** [comment]
I don't know if that is possible because anything in steamvr is handled by something separate which I cannot access, plus forward in steamvr can be changed by doing the setup over again so there's no point in  hard coding it.

**Comment by L3nyxx** [comment]
I see. Well I tried it again and somehow it now has the same forward as the osvr yaw reset does. It runs perpendicular to the arrow which is much more convenient as I only have to turn to the right instead of all the way around.  This issue is solved for me. Thanks!
